### ISSUE TITLE
Build issues in case-insensitive environments.

### ISSUE THREAD

**Issue by loegering** [cliftonlabs/json-simple#13]
#10 was closed but also represents an issue that hasn't been addressed yet. That issue is building json-simple in a case-insensitive file environment like windows. I've copied the workarounds from issue #10 into this issue below:
 
To see the full source in a case insensitive environment, I suggest these workarounds until 3.* is released:
1) Checkout https://cliftonlabs.github.io/json-simple/ to download and import the json-simple project, javadocs, and source JARs into a new project in an IDE of your choosing. This way you can use it and see its javadocs and source in the IDE. However, this won't allow you to contribute to json-simple. This would be the recommended course of action for those that just want to see the source and maybe use it a bit.

2) Do the above with a tool like maven or gradle. Again this won't allow you to contribute to json-simple. This would be the recommended course of action if you're using the library in a project and want to be able to see the javadocs and source while you're developing.

3) I don't recommend it, but it's interesting... windows 10 can differentiate between files with different case with a bash shell environment. You might be able to figure something out from there? You can find more information about it here: https://msdn.microsoft.com/en-us/commandline/wsl/about

4) A dedicated VM (like from Oracle's VirtualBox) for development on json-simple in an OS that does have a case sensitive file API and browser. This would be the recommended course of action for those that want to contribute to json-simple.

I hope this helps. Please share any solutions you've come up with or found so that others may benefit from it too.

**Comment by davsclaus** [comment]
Yeah maybe create a new 2.2.0 release where those deprecated classes from 2.1.x is removed.

**Comment by loegering** [comment]
Unfortunately, removing those deprecated methods is a backwards incompatible change, which would require a major release instead of the minor release suggested. There's quite a few planned features that also break compatibility, so I hope to get those in too before I'm ready to release 3.* so we'll just have to wait until then.

**Comment by loegering** [comment]
Version 3.0.0 is released, fixing this issue.
