### ISSUE TITLE
JsonObject should extend LinkedHashMap

### ISSUE THREAD

**Issue by davsclaus** [cliftonlabs/json-simple#17]
so the order is preserved when elements is added. Currently its a HashMap which has non deterministic ordering.

It would be great if it was a LinkedHashMap then the order is preserved, so the Map has the same order as the json file if you deserialize it.

**Comment by loegering** [comment]
I agree this would be convenient at times, but objects do not have any guarantee on the order of its entries.

https://www.ietf.org/rfc/rfc4627.txt
`An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.`

JSON libraries should not guarantee the order of entries as per the specification. It would also be inadvisable to assume or rely on this behavior since the behavior will not be ubiquitous among JSON libraries.

**Comment by davsclaus** [comment]
It may be so in that spec, but why not allow users to chose if they want that. For example being able to read in a json to java object, and then manipulate a value etc from java, and then save it back to a file, where the file would "look similar", and the only different is what was manipulated from java.

**Comment by loegering** [comment]
I feel it would be beyond the scope of the json-simple library. Adding features to do configuration file manipulation seems specific to the applications that need the configuration file and not a JSON library. There are just so many assumptions that must be made to add the feature that it severely limits how it might help others to the point that they'd have to roll their own anyway.

I've included a code example that might get people started on the right path, that works with plain Java Maps in addition to this library's JsonObjects and only uses this library to write the file.

```
/** Converts Map objects into a LinkedHashMap object using the key order provided.
 * 
 * @param unorderedMap represents a Map that should be ordered. The map will have some values removed as it is copied into an ordered map. Cannot be null.
 * @param keyOrder represents the order of keys that the ordered Map should use. Cannot be null.
 * @return a LinkedHashMap with the explicit keys in the order first, then the remaining unordered map's key value pairs added afterwards in no guaranteed order.
 * @throws IllegalArgumentException if unorderedMap or keyOrder are null.
 */
private static final LinkedHashMap<String, Object> makeOrderedMap(Map<String, Object> unorderedMap, List<String> keyOrder){
	if(unorderedMap == null) {
		throw new IllegalArgumentException("Ordering a map requires an unordered map to order.");
	}
	if(keyOrder == null) {
		throw new IllegalArgumentException("Ordering a map requires a key order to be specified.");
	}
	LinkedHashMap<String, Object> orderedMap = new LinkedHashMap<>();
	/* Explicit ordering. */
	for(String key : keyOrder) {
		if(unorderedMap.entrySet().contains(key)) {
			orderedMap.put(key, unorderedMap.get(key));
			unorderedMap.remove(key);
		}
	}
	/* Assume they didn't care about the ordering of any fields included in the unordered map but not in the keyOrder. */
	for(Map.Entry<String, Object> entry : unorderedMap.entrySet()) {
		orderedMap.put(entry.getKey(), entry.getValue());
	}
	return orderedMap;
}

/** Writes a Map to the file path provided.
 *
 * @param dotJsonPath represents the location of the destination file.
 * @param properties represents the properties of the JSON that will be written to the file.
 * @throws IOException when the file fails to write the JSON string. */
private static final void writeMapIntoJsonObject(final String dotJsonPath, final Map<String, Object> properties) throws IOException{
	/* Sanity check. */
	if(dotJsonPath == null){
		throw new IllegalArgumentException("The file path cannot be null.");
	}
	if(properties == null){
		throw new IllegalArgumentException("The json may not be null.");
	}
	final File dotJson = new File(dotJsonPath);
	if(!dotJson.isDirectory()){
		/* The dotJson file is not a directory. */
		try(BufferedWriter file = new BufferedWriter(new FileWriter(dotJson))){
			/* Write the json string into the file. */
			Jsoner.serialize(properties, file);
			file.flush();
		}
	}
}
```
The above code then could be used with a call like:
```
writeMapIntoJsonObject("/path/to/application/config", makeOrderedMap(new HashMap<>(), new ArrayList<>()));
```
Edit: it could be read back into a JsonObject with the following:
```
/** @param dotJsonPath the location of the source.
 * @return a JsonObject based on the source file.
 * @throws DeserializationException when there is an error parsing JSON.
 * @throws IOException when reading the file fails. */
private static final JsonObject readIntoJsonObject(final String dotJsonPath) throws IOException, DeserializationException{
	/* Sanity check. */
	if(dotJsonPath == null){
		throw new IllegalArgumentException("The file path cannot be null.");
	}
	final Object obj = Jsoner.deserialize(new BufferedReader(new FileReader(new File(dotJsonPath))));
	return (JsonObject)obj;
}
```
/edit
Again this is only one way to do it, and makes a lot of assumptions that may not work for everyone's use case, and honestly has little to do with JSON (as it could have been written without the library entirely).
