### ISSUE TITLE
Allow to configure / specify indent characters when pretty printing

### ISSUE THREAD

**Issue by davsclaus** [cliftonlabs/json-simple#18]
Currently json-simple is hardcoded to use a tab character. It would be nice if you could provide what to use instead, for example 2 x spaces, `"  "` or 4 x spaces `"    "` as a 2nd parameter to the petty method.

**Comment by loegering** [comment]
I like the idea of being able to specify indentation. It will probably be enumerated for tabs, 2 spaces, 3 spaces, and 4 spaces to prevent the method from producing invalid JSON.

**Comment by loegering** [comment]
This was included in the 2.2.0 release.
