### ISSUE TITLE
Memory leak when serialzing huge model to JSON Writer

### ISSUE THREAD

**Issue by davidekholm** [cliftonlabs/json-simple#27]
One of our users is generating a 1GB large JSON data tree to disk. Even though we use the version of the serializer that takes a Writer as parameter, we run out of heap memory. We're using v4.0 of json-simple.

**Comment by davidekholm** [comment]
No reply? Is json-simple abandonware?

**Comment by loegering** [comment]
@davidekholm Sorry had a busy holiday season.
Have you tried adjusting the heap size and ensured you have the appropriate resources on the machine?
https://docs.oracle.com/cd/E19563-01/819-4438/gavou/index.html

**Comment by davidekholm** [comment]
Yes, it fails even with a 4GB heap size.

**Comment by loegering** [comment]
What other fixes have you attempted? Anything that would help me find the issue helps.

**Comment by davidekholm** [comment]
I don't know what workarounds to try. I have a really large JSON tree in RAM that I wish to serialize, but it bails out during that process with an out-of-memory condition. Seems to me that the serialization process could be made more RAM efficient.

**Comment by loegering** [comment]
I was testing with ~10GB files in another issue. Maybe this example of file readers and writers has something to get you in the right direction:
https://github.com/cliftonlabs/json-simple/issues/22

If that doesn't work I can test some large serialization after work.

**Comment by loegering** [comment]
Heya, @davidekholm. I fiddled around with serializing large JSON content.

Keep in mind the original object is also in memory with the buffer to build the serialized output totalling to roughly 3 copies in memory at the end of serialization. I think this is fairly reasonable for in-memory operations using a bulky format like UTF-16 strings. If you need more memory efficiency I recommend a custom binary format instead of JSON for serialization. If you want to use JSON then I recommend doing something like the example in #22 where you serialize it to disk instead of RAM and deserialize into RAM for operations to reduce complete copies in RAM. Strings will still require more resources than a well designed and fitted binary format though.

The following code generates JSON that serializes to roughly 2GB and works with -Xmx6656m (~6.5GB) in less than 1 minute of run time. Feel free to adjust the heap size and loop values to generate something closer to your use cases and hardware profile.
```
public static void main(final String[] args){
	final JsonArray json = new JsonArray();
	final JsonObject content = new JsonObject();
	for(int i = 0; i < 1000; i++){
		content.put("field" + i, "value" + i);
	}
	System.out.println("Built content");
	for(int i = 0; i < 50000; i++){
		json.add(content);
	}
	System.out.println("Added content.");
	String jsonString = Jsoner.serialize(json);
	System.out.println(jsonString.length());
	System.out.println("Done!");
}
```
Basic Hardware profile:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           94
Model name:                      Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Stepping:                        3
CPU MHz:                         800.023
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5199.98
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts 
                                 acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art ar
                                 ch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulq
                                 dq dtes64 monitor ds_cpl est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2
                                 apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault ep
                                 b invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mp
                                 x rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat
                                  pln pts hwp hwp_notify hwp_act_window hwp_epp
               total       used        free         shared    buff/cache    available
Mem:        16215292     7612372     5922492      748416     2680428     7532576
Swap:       15625212           0    15625212

```
Let me know if you need anything else about using Json-Simple.

**Comment by davidekholm** [comment]
Thanks for your pointers. I'll revisit the code if our customer bumps into more issues. I've currently recommended a workaround for the customer that seems  to work fine (splitting a huge project into several smaller projects). You don't need to keep this case open.

**Comment by loegering** [comment]
No problem. Good luck!
