### ISSUE TITLE
Missing files in original repo

### ISSUE THREAD

**Issue by wltjr** [cliftonlabs/json-simple#6]
Have you updated your fork? Seems the original repo has files you are missing like LICENSE, etc. Also seems you are currently updating/maintaining this library. Seems others have forked and made some changes but yours seems to be most complete. I made a MessageBodyHandler for json-simple to be used with Jersey. I was going to send that over to you as a PR for inclusion. Seems it might be of use to others and the main upstream seems dead for a few years now.

**Comment by loegering** [comment]
I've updated the fork to merge the missing files you mention into its own section of the README.txt file. I'm maintaining this library under Clifton Labs and make contributions based on internal needs. Thanks for your contribution and I'll review your pull request when I start working on the next patch.

**Comment by wltjr** [comment]
Ok, I was not aware of the history at the time of the issue. You might want to add a License/Copyright file to your project sources. Github will show the repo has having the license, as well as good habit. I try to follow [GNU base files,](https://en.wikipedia.org/wiki/README). Seems you have much of this, just all in README. Might be cleaner to split that stuff out and just leave instructions and stuff in the README. Up to you. Can close this either way. Thanks for the consideration of this, the PR, and your effort on json-simple updates!

**Comment by wltjr** [comment]
By the way, if you do split the stuff up from Readme. First thing I would suggest in the Readme, along with a description of json-simple, you might want to explain in brief or unabridged history of your work, the previous dead upstream, etc. It took me a little while to see what was going on with json-simple. Not sure if other forks have unified with your efforts. Yours seem most complete and moving forward, thus my interest. Informing others to the history might get them onto the same page and unify things as the current json-simple. Rather than having a bunch of forks with a dead original upstream.

**Comment by loegering** [comment]
Thank you, William, for the feedback. I wanted everything to be in one place (under the README). I wasn't aware those files had meaning to tools like Github though. I'll probably split it again if that is the case. No forks have joined this one yet, but I like your brief history suggestion which might help.
